---
title: "p8105_hw5_cq2207"
author: "Carolina Q Cardoso"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>%
  janitor::clean_names()

```

Write a function that takes a vector as an argument; replaces missing values using the rules defined above; and returns the resulting vector. Apply this function to the columns of iris_with_missing using a map statement.
```{r Problem1}

#For numeric variables, you should fill in missing values with the mean of non-missing values
#For character variables, you should fill in missing values with "virginica" (Species)

fx_fill = function(x) {
  
  if (is.numeric(x))  {
    replace_na(x, mean(x, na.rm = TRUE))
  }
  
  else if (is.character(x)) {
    replace_na(x, "virginica")
  }
  
}

iris_filled = map(iris_with_missing, fx_fill) %>%
  as_tibble()


```


```{r Problem2}

prob2_data =
  list.files("./datasets/", pattern = ".csv", full.names = TRUE) 

data_complete = prob2_data %>%
  map_df(read.csv) %>%
  mutate(file_name = tools::file_path_sans_ext(basename(prob2_data))) %>%
  mutate(
    subject_id = c(1:20), 
    study_arm = ifelse(subject_id == c(1:10), "control", "experimental")
  ) %>%
 select(subject_id, study_arm, file_name, everything()) %>%
select(-file_name) #used name of file to ensure observations were coded correctly as control/experimental
  

```

